/* Generated by CScript Compiler */
/* Do not edit - regenerate from .csr source */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <stdio.h>

enum Color {
    RED,
    GREEN,
    BLUE,
    YELLOW = 10,
    CYAN,
    MAGENTA
};

enum HttpStatus {
    OK = 200,
    CREATED = 201,
    BAD_REQUEST = 400,
    NOT_FOUND = 404,
    INTERNAL_ERROR = 500
};

char* color_name(enum Color c) {
    switch (c) {
    case RED:
        return "Red";
    case GREEN:
        return "Green";
    case BLUE:
        return "Blue";
    case YELLOW:
        return "Yellow";
    case CYAN:
        return "Cyan";
    case MAGENTA:
        return "Magenta";
    default:
        return "Unknown";
    }
}

char* status_message(enum HttpStatus status) {
    switch (status) {
    case OK:
        return "OK";
    case CREATED:
        return "Created";
    case BAD_REQUEST:
        return "Bad Request";
    case NOT_FOUND:
        return "Not Found";
    case INTERNAL_ERROR:
        return "Internal Server Error";
    default:
        return "Unknown Status";
    }
}

int main(void) {
    const enum Color favorite = BLUE;
    const enum HttpStatus response = OK;
    printf("Favorite color: %s (value: %d)\n", color_name(favorite), favorite);
    printf("YELLOW value: %d\n", YELLOW);
    printf("CYAN value: %d\n", CYAN);
    printf("\nHTTP %d: %s\n", response, status_message(response));
    printf("HTTP %d: %s\n", NOT_FOUND, status_message(NOT_FOUND));
    return 0;
}

