/* Generated by CScript Compiler */
/* Do not edit - regenerate from .csr source */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <stdio.h>

int main(void) {
    const int message_count = 5;
    int counter = 0;
    while ((counter < message_count)) {
        printf("Hello, CScript! (%d)\n", counter);
        counter = (counter + 1);
    }
    return 0;
}

