/* Generated by CScript Compiler */
/* Do not edit - regenerate from .csr source */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <stdio.h>

void increment(int* value) {
    (*value) = ((*value) + 1);
}

int double_value(int x) {
    return (x * 2);
}

int main(void) {
    const int max_iterations = 100;
    const int multiplier = 2;
    int counter = 0;
    int total = 0;
    while ((counter < 10)) {
        total = (total + (counter * multiplier));
        increment((&counter));
    }
    printf("Final counter: %d\n", counter);
    printf("Total sum: %d\n", total);
    printf("Doubled max: %d\n", double_value(max_iterations));
    return 0;
}

