/* Generated by CScript Compiler */
/* Do not edit - regenerate from .csr source */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <stdio.h>

#include <stdint.h>

int main(void) {
    const int32_t x = 42;
    const int64_t big = (int64_t)9223372036854775807;
    const uint8_t byte_val = (uint8_t)255;
    const double pi = 3.14159265358979;
    const _Bool is_valid = true;
    const float f = (float)x;
    const int narrowed = (int)big;
    printf("int32: %d\n", x);
    printf("int64: %lld\n", big);
    printf("uint8: %u\n", byte_val);
    printf("float64: %f\n", pi);
    printf("bool: %s\n", (is_valid ? "true" : "false"));
    printf("casted float: %f\n", f);
    printf("narrowed: %d\n", narrowed);
    return 0;
}

